### ISSUE TITLE
Verbose option does not work with ROOT 6.30.04

### ISSUE THREAD

**Issue by amadio** [root-project/analysis-grand-challenge#45]
```
cms-open-data-ttbar $ python analysis.py --ncores 16 -v
Traceback (most recent call last):
  File "/home/amadio/src/analysis-grand-challenge/analyses/cms-open-data-ttbar/analysis.py", line 414, in <module>
    main()
  File "/home/amadio/src/analysis-grand-challenge/analyses/cms-open-data-ttbar/analysis.py", line 342, in main
    ROOT.Detail.RDF.RDFLogChannel.SetVerbosity(ROOT.Experimental.ELogLevel.kInfo)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cppyy.CPPOverload' object has no attribute 'SetVerbosity'
cms-open-data-ttbar $ root --version
ROOT Version: 6.30/04
Built for linuxx8664gcc on Mar 19 2024, 16:35:38
From heads/master@tags/v6-30-04
```
*Note:* doesn't work with conda nightly build either.
